name = "Grassmann"
uuid = "4df31cd9-4c27-5bea-88d0-e6a7146666d8"
version = "0.8.43"
authors = ["Michael Reed"]

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
AbstractTensors = "a8e43f4a-99b7-5565-8bf1-0165161caaea"
ComputedFieldTypes = "459fdd68-db75-56b8-8c15-d717a790f88e"
Cthulhu = "f68482b8-f384-11e8-15f7-abe071a5a75f"
DirectSum = "22fd7b30-a8c0-5bf2-aabe-97783860d07c"
Eyeball = "ce36242b-ad83-4f84-8519-47cd8aeefd60"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
JuliaInterpreter = "aa1ae85d-cabe-5617-a682-6adf51b2e16a"
Leibniz = "edad4870-8a01-11e9-2d75-8f02e448fc59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OhMyREPL = "5fb14364-9ced-5910-84b2-373655c76a03"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
EllipticFunctions = "6a4e32cb-b31a-4929-85af-fb29d9a80738"
FewSpecialFunctions = "6fcbd3ca-4273-49c4-98b3-81b765566de6"
GaloisFields = "8d0d7f98-d412-5cd4-8397-071c807280aa"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Reduce = "93e0c654-6965-5f22-aba9-9c1ae6b3c259"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[extensions]
AbstractAlgebraExt = "AbstractAlgebra"
EllipticFunctionsExt = "EllipticFunctions"
FewSpecialFunctionsExt = "FewSpecialFunctions"
GaloisFieldsExt = "GaloisFields"
GeometryBasicsExt = "GeometryBasics"
LightGraphsExt = "LightGraphs"
MakieExt = "Makie"
MeshesExt = "Meshes"
ReduceExt = "Reduce"
SpecialFunctionsExt = "SpecialFunctions"
StaticArraysExt = "StaticArrays"
SymEngineExt = "SymEngine"
SymPyExt = "SymPy"
SymbolicsExt = "Symbolics"
UnicodePlotsExt = "UnicodePlots"

[compat]
AbstractFFTs = "1"
AbstractTensors = "0.8"
ComputedFieldTypes = "1"
Cthulhu = "3.0.2"
DirectSum = "0.8.12"
Eyeball = "0.5.2"
IJulia = "1.33.0"
JET = "0.11.1"
JuliaFormatter = "1.0.62"
JuliaInterpreter = "0.10.8"
Leibniz = "0.2,0.3"
OhMyREPL = "0.5.32"
PackageCompiler = "2.2.3"
PkgTemplates = "0.7.56"
Pluto = "0.20.21"
Requires = "1"
Revise = "3.12.3"
julia = "1"

[extras]
Adapode = "0750cfb5-909a-49d7-927e-29b6595444bf"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
